spring:
  config:
    import: "classpath:/mysqldatasource.yml"
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/lock-example
      username: root
      password: password
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
logging:
  level:
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.hibernate.SQL: DEBUG
    com.zaxxer.hikari: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework: INFO
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG
